//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halı_Saha_Yönetim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_saha
    {
        public int ID { get; set; }
        public string SAHA_ADI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> KAPASITE { get; set; }
    }
}
