//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halı_Saha_Yönetim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rezervasyon
    {
        public int ID { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public int SAHA_ID { get; set; }
        public string NOT { get; set; }
        public string REZERVASYON_TARIH { get; set; }
        public string REZERVASYON_SAAT { get; set; }
    }
}
